name: lidar_pac
channels:
  - conda-forge
  - defaults
  - anaconda
dependencies:
  - gdal
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - matplotlib
  - ipython
  - jupyter
  - pip
  - black
  - pip:
      - laspy
      - torchnet
      - osgeo
      - codetiming
