name: lidar_pac
channels:
  - conda-forge
  - defaults
  - anaconda
  - dmentipl 
dependencies:
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - matplotlib
  - ipython
  - jupyter
  - pip
  - black
  - tqdm
  - rasterio
  - numpy-indexed
  - kdepy
  - pip:
      - gdal
      - laspy=1.7.0
      - torchnet
      - codetiming
